movies/urls.py
from django.urls import include, path

from . import views

app_name = "movies"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
]

simplesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("movies/", include("movies.urls")),
]

movies/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    year = models.IntegerField()
    poster = models.URLField()
    trailer = models.URLField()

    def __str__(self):
        return self.title


class Actor(models.Model):
    name = models.CharField(max_length=100)
    imdb_page = models.URLField()
    was_in = models.ManyToManyField("Movie", related_name="actors")

    def __str__(self):
        return self.name

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

movies/forms.py
from crispy_forms.helper import FormHelper
from django import forms


class MovieSearch(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "GET"
        self.helper.form_action = "submit_form"
        self.helper.form_id = "id-searchMovie"

    title = forms.CharField(max_length=100)


class MoviePOSTForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "POST"
        self.helper.form_action = "submit_form"
        self.helper.form_id = "id-getForm"

    title = forms.CharField(max_length=100)
    description = forms.TextField()
    year = forms.IntegerField()
    poster = forms.URLField()
    trailer = forms.URLField()

movies/views.py
from django.shortcuts import render
from django.views import generic

from .models import Movie


# Create your views here.
class IndexView(generic.ListView):
    template_name = "movies/index.html"
    context_object_name = "latest_movie_list"

    def get_queryset(self):
        return Movie.objects.order_by("-year")[:50]


class DetailView(generic.DetailView):
    model = Movie
    template_name = "movies/detail.html"

users/views.py
from django.shortcuts import render

# Create your views here.

movies/templates/movies/base.html
<html>
  <head>
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}{% endblock %}
  </head>
  <body>
    {% block content %} This is a page {% endblock %}
  </body>
</html>

movies/templates/movies/detail.html
{% extends 'movies/base.html' %} {% block title %} {{ movie.title }} {% endblock %} 
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>{{ movie.title }} ({{ movie.year }})</h1>
      <p>{{ movie.description }}</p>
      <p>{{ message }}</p>
      {% if movie.poster %}
      <img src="{{ movie.poster }}" class="img-responsive" width="300" />
      {% endif %} 
      
    </div>
  </div>
</div>
{% endblock %}

movies/templates/movies/index.html
{% extends 'movies/base.html' %} {% block title %} Latest Movies {% endblock %} 
{% block content %}
<ul>
{% for movie in latest_movie_list %}
<li><a href="{% url "movies:detail" movie.id %}">{{ movie.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

movies/templates/movies/movie_get_form.html
{% block title %}Add a movie (GET){% endblock %}

{% block content %}
<form action="{% url "movies:submitget" %}" method="get">
    
</form>
{% endblock %}